### PR TITLE
[+]CNN Model

### PR DESCRIPTION
**Pull request by MostlyKIGuess**

### CODE REVIEW

**Comment by MostlyKIGuess** [comment]
[+] Config Instructions added.
[-] Removed the dataset.
[+] Model Performance added.

**Comment by 0x0is1** [comment]
Github couldn't render changes

**Comment by MostlyKIGuess** [comment]
> Github couldn't render changes

It should be able to do now right?
The 5 files chnaged.

**Comment by MostlyKIGuess** [comment]
The CNN Model Added commit should have the issue ig.

**Comment by 0x0is1** [comment]
I see no extra commits. What are you on about

**Comment by MostlyKIGuess** [comment]
> I see no extra commits. What are you on about

image

**Review by 0x0is1 — APPROVED** [review]
Fair

**Comment by 0x0is1** [comment]
LGTM

**Pull request merged**
